# Generated by Django 5.2.7 on 2025-11-17 09:40

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0003_update_idempotency_scope_and_constraints"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentIntent",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("provider", models.CharField(default="paystack", max_length=32)),
                ("reference", models.CharField(db_index=True, max_length=64, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=12)),
                ("currency", models.CharField(default="NGN", max_length=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("initialized", "Initialized"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="initialized",
                        max_length=16,
                    ),
                ),
                ("authorization_url", models.URLField(blank=True)),
                ("access_code", models.CharField(blank=True, max_length=64)),
                ("metadata", models.JSONField(blank=True, null=True)),
                ("webhook_event", models.JSONField(blank=True, null=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payment_intents", to="orders.order"
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
            },
        ),
        migrations.AddIndex(
            model_name="paymentintent",
            index=models.Index(fields=["order", "status", "created_at"], name="payments_pa_order_i_e6141c_idx"),
        ),
    ]
