# Generated by Django 5.2.7 on 2025-11-19 01:04

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0002_paymentintent_constraints_indexes"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="paymentintent",
            new_name="payments_pa_order_i_f92a4d_idx",
            old_name="payments_pa_order_i_e6141c_idx",
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="currency",
            field=models.CharField(
                choices=[
                    ("NGN", "Nigerian Naira"),
                    ("USD", "US Dollar"),
                    ("GHS", "Ghanaian Cedi"),
                    ("ZAR", "South African Rand"),
                    ("KES", "Kenyan Shilling"),
                    ("XOF", "West African CFA Franc"),
                ],
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="paymentintent",
            name="provider",
            field=models.CharField(choices=[("paystack", "Paystack")], default="paystack", max_length=32),
        ),
    ]
