# Generated by Django 5.2.7 on 2025-11-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0004_user_pending_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["pending_email"], name="users_user_pending_c96082_idx"),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(("pending_email__isnull", False)),
                fields=("pending_email",),
                name="unique_pending_email_non_null",
            ),
        ),
    ]
