# Generated by Django 5.2.7 on 2025-11-10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Primary contact number for the account in E.164 format",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        r"^\+?[1-9]\d{1,14}$",
                        message="Use E.164 format (e.g., +14155552671)",
                    )
                ],
            ),
        ),
    ]
