# Generated by Django 5.2.7 on 2025-11-10 11:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(
                        blank=True, help_text="Optional recipient or label for the address", max_length=120
                    ),
                ),
                ("line1", models.CharField(max_length=120)),
                ("line2", models.CharField(blank=True, max_length=120)),
                ("city", models.CharField(max_length=80)),
                ("region", models.CharField(blank=True, help_text="State/Province/Region", max_length=80)),
                ("postal_code", models.CharField(max_length=20)),
                (
                    "country_code",
                    models.CharField(
                        help_text="ISO 3166-1 alpha-2 (e.g., US, CA)",
                        max_length=2,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{2}$", message="Use ISO 3166-1 alpha-2 country code (e.g., US)"
                            )
                        ],
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[1-9]\\d{1,14}$", message="Use E.164 phone format (e.g., +14155552671)"
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        max_length=16,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\+?[1-9]\\d{1,14}$", message="Use E.164 phone format (e.g., +14155552671)"
                            )
                        ],
                    ),
                ),
                ("marketing_opt_in", models.BooleanField(default=False)),
                ("sms_opt_in", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "default_billing_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="billing_profiles",
                        to="customer.address",
                    ),
                ),
                (
                    "default_shipping_address",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipping_profiles",
                        to="customer.address",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="profile", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user", "country_code", "postal_code"], name="customer_ad_user_id_341913_idx"),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user", "city"], name="customer_ad_user_id_6218a5_idx"),
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("user", "line1", "city", "postal_code", "country_code"), name="unique_address_per_user"
            ),
        ),
        migrations.AddIndex(
            model_name="profile",
            index=models.Index(fields=["user"], name="customer_pr_user_id_4fa605_idx"),
        ),
    ]
