# Generated by Django 5.2.7 on 2025-11-10 12:19

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="region",
        ),
        migrations.AddField(
            model_name="address",
            name="state",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Abia", "Abia"),
                    ("Adamawa", "Adamawa"),
                    ("Akwa Ibom", "Akwa Ibom"),
                    ("Anambra", "Anambra"),
                    ("Bauchi", "Bauchi"),
                    ("Bayelsa", "Bayelsa"),
                    ("Benue", "Benue"),
                    ("Borno", "Borno"),
                    ("Cross River", "Cross River"),
                    ("Delta", "Delta"),
                    ("Ebonyi", "Ebonyi"),
                    ("Edo", "Edo"),
                    ("Ekiti", "Ekiti"),
                    ("Enugu", "Enugu"),
                    ("Gombe", "Gombe"),
                    ("Imo", "Imo"),
                    ("Jigawa", "Jigawa"),
                    ("Kaduna", "Kaduna"),
                    ("Kano", "Kano"),
                    ("Katsina", "Katsina"),
                    ("Kebbi", "Kebbi"),
                    ("Kogi", "Kogi"),
                    ("Kwara", "Kwara"),
                    ("Lagos", "Lagos"),
                    ("Nasarawa", "Nasarawa"),
                    ("Niger", "Niger"),
                    ("Ogun", "Ogun"),
                    ("Ondo", "Ondo"),
                    ("Osun", "Osun"),
                    ("Oyo", "Oyo"),
                    ("Plateau", "Plateau"),
                    ("Rivers", "Rivers"),
                    ("Sokoto", "Sokoto"),
                    ("Taraba", "Taraba"),
                    ("Yobe", "Yobe"),
                    ("Zamfara", "Zamfara"),
                    ("FCT", "FCT"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="nin",
            field=models.CharField(
                blank=True,
                help_text="Optional National Identification Number (11 digits)",
                max_length=11,
                null=True,
                unique=True,
                validators=[django.core.validators.RegexValidator("^\\d{11}$", message="NIN must be 11 digits")],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="country_code",
            field=models.CharField(
                choices=[("NG", "Nigeria")],
                default="NG",
                help_text="ISO 3166-1 alpha-2; fixed to Nigeria",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+234\\d{10}$", message="Use Nigerian E.164 format (+234XXXXXXXXXX)"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                max_length=6,
                validators=[
                    django.core.validators.RegexValidator("^\\d{6}$", message="Use 6-digit Nigerian postal code")
                ],
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+234\\d{10}$", message="Use Nigerian E.164 format (+234XXXXXXXXXX)"
                    )
                ],
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user", "state"], name="customer_ad_user_id_12171c_idx"),
        ),
    ]
