# Generated by Django 5.2.7 on 2025-11-10 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_remove_address_region_address_state_profile_nin_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="address",
            name="unique_address_per_user",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="line1",
            new_name="addr1",
        ),
        migrations.RenameField(
            model_name="address",
            old_name="line2",
            new_name="addr2",
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                fields=("user", "addr1", "city", "postal_code", "country_code"), name="unique_address_per_user"
            ),
        ),
    ]
