# Generated by Django 5.2.7 on 2025-11-10 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_remove_address_unique_address_per_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="marketing_opt_in",
            new_name="email_opt_in",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="nin",
        ),
    ]
