# Generated by Django 5.2.7 on 2025-11-10 15:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_rename_marketing_opt_in_profile_email_opt_in_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="address",
            name="country_code",
            field=models.CharField(
                default="NG",
                help_text="ISO 3166-1 alpha-2",
                max_length=2,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Z]{2}$", message="Use ISO 3166-1 alpha-2 country code (e.g., US)"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Contact number for this specific address/recipient",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[1-9]\\d{1,14}$", message="Use E.164 format (e.g., +14155552671)"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="postal_code",
            field=models.CharField(
                blank=True,
                help_text="Flexible postal/zip code",
                max_length=12,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[A-Za-z0-9\\- ]{0,12}$", message="Use standard alphanumeric postal/zip code"
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="address",
            name="state",
            field=models.CharField(
                blank=True,
                help_text="State/Province/Region (free-form to support multiple countries)",
                max_length=40,
                null=True,
            ),
        ),
    ]
