# Generated by Django 5.2.7 on 2025-11-10 15:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_alter_address_country_code_alter_address_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Primary contact number for the account in E.164 format",
                max_length=16,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\+?[1-9]\\d{1,14}$", message="Use E.164 format (e.g., +14155552671)"
                    )
                ],
            ),
        ),
    ]
