# Generated by Django 5.2.7 on 2025-11-10

from django.db import migrations


def forwards(apps, schema_editor):
    Profile = apps.get_model("customer", "Profile")
    # Copy non-empty profile phones into user.phone, without overwriting existing user.phone
    for profile in Profile.objects.all().iterator():
        phone = getattr(profile, "phone", "") or ""
        if phone:
            user = profile.user
            if not getattr(user, "phone", ""):
                user.phone = phone.strip()
                user.save(update_fields=["phone"])


def backwards(apps, schema_editor):
    # No-op: cannot reliably restore profile.phone after removal
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_profile_phone"),
        ("users", "0006_add_user_phone"),
    ]

    operations = [
        migrations.RunPython(forwards, backwards),
    ]
