# Generated by Django 5.2.7 on 2025-11-10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_backfill_user_phone"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
