# Generated by Django 5.2.7 on 2025-11-09 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0007_remove_productvariant_variant_stock_non_negative_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockItem",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField(default=0)),
                ("reserved", models.IntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=16
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.product"
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="catalog.productvariant"
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[("in", "Inbound"), ("out", "Outbound"), ("adjust", "Adjust")], max_length=16
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("reason", models.CharField(blank=True, max_length=200)),
                ("reference", models.CharField(blank=True, max_length=120)),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="movements", to="inventory.stockitem"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["product", "variant", "status"], name="inventory_s_product_5c39f6_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gte", 0)), name="stock_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(condition=models.Q(("reserved__gte", 0)), name="reserved_non_negative"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved__lte", models.F("quantity"))), name="reserved_le_quantity"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("product__isnull", False), ("variant__isnull", True)),
                    models.Q(("product__isnull", True), ("variant__isnull", False)),
                    _connector="OR",
                ),
                name="stockitem_xor_product_variant",
            ),
        ),
    ]
