# Generated by Django 5.2.7 on 2025-11-09 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_productvariant_options"),
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockReservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.IntegerField()),
                ("reference", models.CharField(max_length=120)),
                (
                    "state",
                    models.CharField(
                        choices=[("active", "Active"), ("released", "Released"), ("converted", "Converted")],
                        default="active",
                        max_length=16,
                    ),
                ),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at", "id"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="stockitem",
            name="stockitem_xor_product_variant",
        ),
        migrations.RemoveIndex(
            model_name="stockitem",
            name="inventory_s_product_5c39f6_idx",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="product",
        ),
        migrations.RemoveField(
            model_name="stockitem",
            name="status",
        ),
        migrations.AddIndex(
            model_name="stockitem",
            index=models.Index(fields=["variant"], name="inventory_s_variant_6b6541_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(fields=("variant",), name="unique_stockitem_per_variant"),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("variant__isnull", False)), name="stockitem_variant_not_null"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockmovement",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity", 0), _negated=True), name="movement_non_zero"
            ),
        ),
        migrations.AddField(
            model_name="stockreservation",
            name="variant",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="catalog.productvariant"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["variant"], name="inventory_s_variant_fdfe16_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["expires_at"], name="inventory_s_expires_9d6a1b_idx"),
        ),
        migrations.AddIndex(
            model_name="stockreservation",
            index=models.Index(fields=["reference"], name="inventory_s_referen_3256ca_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockreservation",
            constraint=models.CheckConstraint(condition=models.Q(("quantity__gt", 0)), name="reservation_positive_qty"),
        ),
    ]
