# Generated by Django 5.2.7 on 2025-11-06 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "NGN"), ("USD", "USD"), ("EUR", "EUR")], default="NGN", max_length=3
            ),
        ),
        migrations.AlterField(
            model_name="productvariant",
            name="currency",
            field=models.CharField(
                choices=[("NGN", "NGN"), ("USD", "USD"), ("EUR", "EUR")], default="NGN", max_length=3
            ),
        ),
    ]
