# Generated by Django 5.2.7 on 2025-11-06 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_product_currency_alter_productvariant_currency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="collection",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[("draft", "Draft"), ("published", "Published")], db_index=True, default="draft", max_length=16
            ),
        ),
        migrations.CreateModel(
            name="CollectionProduct",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("sort_order", models.IntegerField(default=0)),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_products",
                        to="catalog.collection",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collection_products",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "unique_together": {("collection", "product")},
            },
        ),
        migrations.AddField(
            model_name="collection",
            name="ordered_products",
            field=models.ManyToManyField(
                blank=True,
                related_name="ordered_collections",
                through="catalog.CollectionProduct",
                to="catalog.product",
            ),
        ),
    ]
