# Generated by Django 5.2.7 on 2025-11-07 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_category_is_active_alter_collection_is_active_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="collection",
            name="products",
        ),
    ]
