# Generated by Django 5.2.7 on 2025-11-09 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_collection_products"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="collectionproduct",
            index=models.Index(fields=["collection", "sort_order"], name="catalog_col_collect_44ef17_idx"),
        ),
        migrations.AddIndex(
            model_name="media",
            index=models.Index(fields=["product", "sort_order", "is_primary"], name="catalog_med_product_b62548_idx"),
        ),
        migrations.AddIndex(
            model_name="productattributevalue",
            index=models.Index(fields=["attribute", "product", "variant"], name="catalog_pro_attribu_888a9c_idx"),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True), ("variant__isnull", True)),
                fields=("product",),
                name="unique_primary_media_per_product",
            ),
        ),
        migrations.AddConstraint(
            model_name="media",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)), fields=("variant",), name="unique_primary_media_per_variant"
            ),
        ),
        migrations.AddConstraint(
            model_name="productattributevalue",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("product__isnull", False), ("variant__isnull", True)),
                    models.Q(("product__isnull", True), ("variant__isnull", False)),
                    _connector="OR",
                ),
                name="pav_xor_product_variant",
            ),
        ),
    ]
