# Generated by Django 5.2.7 on 2025-11-09 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_collectionproduct_catalog_col_collect_44ef17_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="reserved_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="stock_quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "status"], name="catalog_pro_product_7cdb45_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("stock_quantity__gte", 0)), name="variant_stock_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__gte", 0)), name="variant_reserved_non_negative"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("reserved_quantity__lte", models.F("stock_quantity"))),
                name="variant_reserved_le_stock",
            ),
        ),
    ]
