# Generated by Django 5.2.7 on 2025-11-09 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_productvariant_reserved_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="variant_stock_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="variant_reserved_non_negative",
        ),
        migrations.RemoveConstraint(
            model_name="productvariant",
            name="variant_reserved_le_stock",
        ),
        migrations.RemoveIndex(
            model_name="productvariant",
            name="catalog_pro_product_7cdb45_idx",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="reserved_quantity",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="stock_quantity",
        ),
    ]
