# Generated by Django 5.2.7 on 2025-11-09 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_remove_productvariant_variant_stock_non_negative_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="default_price",
        ),
        migrations.RemoveField(
            model_name="productvariant",
            name="currency",
        ),
    ]
