# Generated by Django 5.2.7 on 2025-11-09 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_remove_product_default_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="currency",
            field=models.CharField(default="NGN", max_length=3),
        ),
    ]
