# Generated by Django 5.2.7 on 2025-11-09 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_alter_product_currency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="currency",
        ),
    ]
