# Generated by Django 5.2.7 on 2025-11-09 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_remove_productvariant_options"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="productvariant",
            index=models.Index(fields=["product", "status"], name="catalog_pro_product_7cdb45_idx"),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(("price__gte", 0), ("price__isnull", True), _connector="OR"),
                name="variant_price_non_negative",
            ),
        ),
    ]
