# Generated by Django 5.2.7 on 2025-11-12 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("inventory", "0002_stockreservation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="reservation_id",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="reservation",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="inventory.stockreservation",
            ),
        ),
    ]
