# Generated by Django 5.2.7 on 2025-11-13

import django.db.models.deletion
from common.choices import CartStatus
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0002_remove_cartitem_reservation_id_cartitem_reservation"),
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="carts",
                to="users.user",
            ),
        ),
        migrations.AddField(
            model_name="cart",
            name="session_id",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddIndex(
            model_name="cart",
            index=models.Index(fields=["session_id", "status"], name="cart_cart_session_id_status_idx"),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.CheckConstraint(
                name="cart_user_xor_session",
                check=(
                    (models.Q(("user__isnull", False)) & models.Q(("session_id__isnull", True)))
                    | (models.Q(("user__isnull", True)) & models.Q(("session_id__isnull", False)))
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=["user", "status"],
                condition=models.Q(("status", CartStatus.ACTIVE)),
                name="unique_active_cart_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="cart",
            constraint=models.UniqueConstraint(
                fields=["session_id", "status"],
                condition=models.Q(("status", CartStatus.ACTIVE)),
                name="unique_active_cart_per_session",
            ),
        ),
    ]
