# Generated by Django 5.2.7 on 2025-11-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0003_guest_carts"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="cart",
            new_name="cart_cart_session_31bbdf_idx",
            old_name="cart_cart_session_id_status_idx",
        ),
    ]
