# Generated by Django 5.2.7 on 2025-11-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_total",
        ),
        migrations.RemoveField(
            model_name="order",
            name="shipping_total",
        ),
        migrations.RemoveField(
            model_name="order",
            name="subtotal",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tax_total",
        ),
        migrations.RemoveField(
            model_name="order",
            name="total",
        ),
    ]
