# Generated by Django 5.2.7 on 2025-11-19 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0004_order_address_and_status_events"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="orderstatusevent",
            new_name="orders_orde_order_i_1e3f4d_idx",
            old_name="orders_event_order_created_idx",
        ),
    ]
